version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: pontohub-postgres-dev
    restart: unless-stopped
    environment:
      POSTGRES_DB: pontohub_portal_dev
      POSTGRES_USER: pontohub_user
      POSTGRES_PASSWORD: pontohub_password
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - pontohub-dev-network

  # Redis for caching and sessions
  redis:
    image: redis:7-alpine
    container_name: pontohub-redis-dev
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - redis_dev_data:/data
    ports:
      - "6379:6379"
    networks:
      - pontohub-dev-network

  # Backend API (development mode)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: pontohub-backend-dev
    restart: unless-stopped
    environment:
      NODE_ENV: development
      PORT: 3001
      DATABASE_URL: postgresql://pontohub_user:pontohub_password@postgres:5432/pontohub_portal_dev
      REDIS_URL: redis://redis:6379
      JWT_SECRET: dev-jwt-secret-key
      JWT_REFRESH_SECRET: dev-refresh-secret-key
      JWT_EXPIRES_IN: 24h
      JWT_REFRESH_EXPIRES_IN: 7d
      CORS_ORIGIN: http://localhost:3000
    ports:
      - "3001:3001"
    depends_on:
      - postgres
      - redis
    networks:
      - pontohub-dev-network
    volumes:
      - ./backend:/app
      - /app/node_modules
      - backend_dev_uploads:/app/uploads

  # Frontend Application (development mode)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: pontohub-frontend-dev
    restart: unless-stopped
    environment:
      NODE_ENV: development
      NEXT_PUBLIC_API_URL: http://localhost:3001
      NEXT_PUBLIC_APP_NAME: "PontoHub Portal (Dev)"
      NEXT_PUBLIC_APP_VERSION: "1.0.0-dev"
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - pontohub-dev-network
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next

volumes:
  postgres_dev_data:
    driver: local
  redis_dev_data:
    driver: local
  backend_dev_uploads:
    driver: local

networks:
  pontohub-dev-network:
    driver: bridge

